export const dataDemo = [
  {
    _id: 0,
    name: "Kệ TV",
    glbUrl: "./assets/demo/glb/DARELL-G-2M4.glb",
    // glbUrl: "./assets/demo/glb/ke-tivi-3.glb",
    iconUrl: "./assets/demo/icon/ke-tivi-2.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ke-tivi-3.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-3.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        iconUrl: "./assets/demo/img/ke-tivi-2.jpg",
        imgUrl: "./assets/demo/img/ke-tivi-2.jpg",
      },
      {
        id: 2,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/ke-tivi-1.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-1.jpg",
      },
      {
        id: 3,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/HH186-2.png",
        iconUrl: "./assets/demo/img/HH186-2.png",
      },
      {
        id: 4,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/HH186-39.png",
        iconUrl: "./assets/demo/img/HH186-39.png",
      },
      {
        id: 5,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/HH186-38.png",
        iconUrl: "./assets/demo/img/HH186-38.png",
      },
      {
        id: 6,
        name: "Texture 2048",
        imgUrl: "./assets/demo/img/2048.jpg",
        iconUrl: "./assets/demo/img/2048.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
  {
    _id: 1,
    name: "Bàn trà đôi",
    glbUrl: "./assets/demo/glb/ban-tra-doi-tron.glb",
    iconUrl: "./assets/demo/icon/ban-tra-doi-tron.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ban-tra-doi-tron-1.jpg",
        iconUrl: "./assets/demo/img/ban-tra-doi-tron-1.jpg",
      },
    ],
    price: 3000000,
    description: "",
  },
  {
    _id: 2,
    name: "Bàn trà vuông",
    glbUrl: "./assets/demo/glb/ban-tra-vuong.glb",
    iconUrl: "./assets/demo/icon/ban-tra-vuong.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ban-tra-vuong-1.jpg",
        iconUrl: "./assets/demo/img/ban-tra-vuong-1.jpg",
      },
    ],
    price: 2800000,
    description: "",
  },
  {
    _id: 3,
    name: "Avalon",
    // glbUrl: "./assets/demo/glb/avalon.glb",
    glbUrl: "./assets/demo/glb/ZINKAN-B-2M.glb",
    iconUrl: "./assets/demo/icon/avalon.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/avalon-1.jpg",
        iconUrl: "./assets/demo/img/avalon-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/HH186-38.png",
        iconUrl: "./assets/demo/img/HH186-38.png",
      },
      {
        id: 2,
        name: "Texture 3",
        imgUrl: "./assets/demo/img/HH186-39.png",
        iconUrl: "./assets/demo/img/HH186-39.png",
      },
      {
        id: 3,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/HH186-21.png",
        iconUrl: "./assets/demo/img/HH186-21.png",
      },
    ],
    price: 4500000,
    description: "",
  },
  {
    _id: 4,
    name: "Tobias",
    // glbUrl: "./assets/demo/glb/tobias.glb",
    glbUrl: "./assets/demo/glb/ZINKAN-B-2M-HH18638.glb",
    iconUrl: "./assets/demo/icon/tobias.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/tobias-1.jpg",
        iconUrl: "./assets/demo/img/tobias-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/tobias-2.jpg",
        iconUrl: "./assets/demo/img/tobias-2.jpg",
      },
      {
        id: 2,
        name: "Texture 3",
        imgUrl: "./assets/demo/img/tobias-3.jpg",
        iconUrl: "./assets/demo/img/tobias-3.jpg",
      },
      {
        id: 3,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/tobias-4.jpg",
        iconUrl: "./assets/demo/img/tobias-4.jpg",
      },
    ],
    price: 5000000,
    description: "",
  },
  {
    _id: 5,
    name: "fallyn",
    glbUrl: "./assets/demo/glb/fallyn.glb",
    iconUrl: "./assets/demo/icon/fallyn.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/fallyn-1.jpg",
        iconUrl: "./assets/demo/img/fallyn-1.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
  {
    _id: 6,
    name: "Scott",
    glbUrl: "./assets/demo/glb/scott.glb",
    iconUrl: "./assets/demo/icon/scott.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/scott-1.jpg",
        iconUrl: "./assets/demo/img/scott-1.jpg",
      },
      // {
      //   id: 1,
      //   name: "Texture 2",
      //   imgUrl: "./assets/demo/img/scott-2.jpg",
      //   iconUrl: "./assets/demo/img/scott-2.jpg",
      // },
      // {
      //   id: 2,
      //   name: "Texture 3",
      //   imgUrl: "./assets/demo/img/scott-3.jpg",
      //   iconUrl: "./assets/demo/img/scott-3.jpg",
      // },
      // {
      //   id: 3,
      //   name: "Texture 4",
      //   imgUrl: "./assets/demo/img/scott-4.jpg",
      //   iconUrl: "./assets/demo/img/scott-4.jpg",
      // },
      {
        id: 1,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/1.jpg",
        iconUrl: "./assets/demo/img/1.jpg",
      },
      {
        id: 2,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/2.jpg",
        iconUrl: "./assets/demo/img/2.jpg",
      },
      {
        id: 3,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/3.jpg",
        iconUrl: "./assets/demo/img/3.jpg",
      },
    ],
    price: 6000000,
    description: "",
  },
  {
    _id: 7,
    name: "Arni",
    glbUrl: "./assets/demo/glb/arni.glb",
    iconUrl: "./assets/demo/icon/arni.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/arni-1.jpg",
        iconUrl: "./assets/demo/img/arni-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/arni-2.jpg",
        iconUrl: "./assets/demo/img/arni-2.jpg",
      },
      {
        id: 2,
        name: "Texture 3",
        imgUrl: "./assets/demo/img/arni-3.jpg",
        iconUrl: "./assets/demo/img/arni-3.jpg",
      },
      {
        id: 3,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/arni-4.jpg",
        iconUrl: "./assets/demo/img/arni-4.jpg",
      },
    ],
    price: 9000000,
    description: "",
  },
  {
    _id: 8,
    name: "zita",
    glbUrl: "./assets/demo/glb/zita.glb",
    iconUrl: "./assets/demo/icon/zita.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/zita-1.jpg",
        iconUrl: "./assets/demo/img/zita-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/zita-2.jpg",
        iconUrl: "./assets/demo/img/zita-2.jpg",
      },
      {
        id: 2,
        name: "Texture 3",
        imgUrl: "./assets/demo/img/zita-3.jpg",
        iconUrl: "./assets/demo/img/zita-3.jpg",
      },
      {
        id: 3,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/zita-4.jpg",
        iconUrl: "./assets/demo/img/zita-4.jpg",
      },
    ],
    price: 5000000,
    description: "",
  },
  {
    _id: 9,
    name: "Tobias xanh đen",
    glbUrl: "./assets/demo/glb/tobias-xd.glb",
    iconUrl: "./assets/demo/icon/temp-4.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/tobias-3.jpg",
        iconUrl: "./assets/demo/img/tobias-3.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
  {
    _id: 10,
    name: "Tobias hồng",
    glbUrl: "./assets/demo/glb/tobias-h.glb",
    iconUrl: "./assets/demo/icon/temp-1.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/tobias-4.jpg",
        iconUrl: "./assets/demo/img/tobias-4.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
  {
    _id: 11,
    name: "Scott",
    glbUrl: "./assets/demo/glb/scott.glb",
    iconUrl: "./assets/demo/icon/scott.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/scott-1.jpg",
        iconUrl: "./assets/demo/img/scott-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/scott-2.jpg",
        iconUrl: "./assets/demo/img/scott-2.jpg",
      },
      {
        id: 2,
        name: "Texture 3",
        imgUrl: "./assets/demo/img/scott-3.jpg",
        iconUrl: "./assets/demo/img/scott-3.jpg",
      },
      {
        id: 3,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/scott-4.jpg",
        iconUrl: "./assets/demo/img/scott-4.jpg",
      },
    ],
    price: 6000000,
    description: "",
  },
  {
    _id: 12,
    name: "Avalon",
    glbUrl: "./assets/demo/glb/avalon.glb",
    iconUrl: "./assets/demo/icon/avalon.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/avalon-1.jpg",
        iconUrl: "./assets/demo/img/avalon-1.jpg",
      },
    ],
    price: 4500000,
    description: "",
  },
  {
    _id: 13,
    name: "Bàn trà đôi",
    glbUrl: "./assets/demo/glb/ban-tra-doi-tron.glb",
    iconUrl: "./assets/demo/icon/ban-tra-doi-tron.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ban-tra-doi-tron-1.jpg",
        iconUrl: "./assets/demo/img/ban-tra-doi-tron-1.jpg",
      },
    ],
    price: 3000000,
    description: "",
  },
  {
    _id: 14,
    name: "Bàn trà vuông",
    glbUrl: "./assets/demo/glb/ban-tra-vuong.glb",
    iconUrl: "./assets/demo/icon/ban-tra-vuong.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ban-tra-vuong-1.jpg",
        iconUrl: "./assets/demo/img/ban-tra-vuong-1.jpg",
      },
    ],
    price: 2800000,
    description: "",
  },
  {
    _id: 15,
    name: "Tobias",
    glbUrl: "./assets/demo/glb/tobias.glb",
    iconUrl: "./assets/demo/icon/tobias.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/tobias-1.jpg",
        iconUrl: "./assets/demo/img/tobias-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/tobias-2.jpg",
        iconUrl: "./assets/demo/img/tobias-2.jpg",
      },
      {
        id: 2,
        name: "Texture 3",
        imgUrl: "./assets/demo/img/tobias-3.jpg",
        iconUrl: "./assets/demo/img/tobias-3.jpg",
      },
      {
        id: 3,
        name: "Texture 4",
        imgUrl: "./assets/demo/img/tobias-4.jpg",
        iconUrl: "./assets/demo/img/tobias-4.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
  {
    _id: 16,
    name: "Kệ TV",
    glbUrl: "./assets/demo/glb/ke-tivi-1.glb",
    iconUrl: "./assets/demo/icon/ke-tivi-1.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ke-tivi-1.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/ke-tivi-2.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-2.jpg",
      },
      {
        id: 2,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/ke-tivi-3.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-3.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
  {
    _id: 17,
    name: "Tobias hồng",
    glbUrl: "./assets/demo/glb/ke-tivi.glb",
    iconUrl: "./assets/demo/icon/temp-1.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ke-tivi-1.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/ke-tivi-2.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-2.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
  {
    _id: 18,
    name: "Tobias xanh đen",
    glbUrl: "./assets/demo/glb/ke-tivi.glb",
    iconUrl: "./assets/demo/icon/temp-4.png",
    listTexture: [
      {
        id: 0,
        name: "Texture 1",
        imgUrl: "./assets/demo/img/ke-tivi-1.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-1.jpg",
      },
      {
        id: 1,
        name: "Texture 2",
        imgUrl: "./assets/demo/img/ke-tivi-2.jpg",
        iconUrl: "./assets/demo/img/ke-tivi-2.jpg",
      },
    ],
    price: 3500000,
    description: "",
  },
];
